const blogPaths = [
    "/blog",
    "/contact",
    "/news",
    "/previews",
    "/reviews",
    "/video",
    "/videos",
    "/platform",
    "/posts",
    "/sidebar",
    "/gallery",
    "/audio",
    "/links",
    "/quotes",
    "/blog audio",
    "/video blog",
    "/blog links",
    "/sidebar format",
    "/settings",
    "/video sidebar",
    "/XBOX will make a new controller at 2022",
    "/Uncharted 4: A Thief's End will release on PC at 2021",
    "/Need For Speed: Rivals will shutdown servers at 2023",
    `/"PS4 PRO THE LAST OF US PART II EDITION released right now!" - Sony`,
    "/Epic Games updated store. Added 40 sales",
    "/New XBOX special edition controller",
    "/Need For Speed: Payback got update",
    "/Need For Speed: ProStreet the last good EA game...",
    "/Battlefield V released on PS4. Is it good",
    "/Cyberpunk 2077 need patches and fixes",
    "/Forza Horizon 3 better than Need For Speed: Hot Pursuit",
    "/Gears Of War on XBOX in 4K",
    "/FIFA 22 coming soon...",
    "/Fallout 4 the best Fallout ever!",
    "/Call Of Duty Black Ops III updated!",
    "/page 3",
    "/Fallout 4",
    "/Gears of War",
    "/World of Warcraft Warlords of Draenor",
    "/Need for Speed: Rivals",
    "/Fallout 3",
    "/Call of Duty: Warzone",
    "/Driver San Francisco",
    "/Diablo III",
    "/information",
    "/recent post",
    "/platforms",
    "/contact us",
    "/comment 0",
    "/comment 1",
    "/comment 2",
    "/comment 3",
    "/comment 4",
    "/comment 5",
    "/comment 6",
    "/comment 7",
    "/Far Cry Primal's map is made from Far Cry 4",
    "/The Division Xbox One, PS4, PC file sizes revealed",
    "/Manual transmission as a part of Need for Speed's update",
    "/Mass Effect: Andromeda to miss holiday 2016 release",
    "/Gears of War: Ultimate Edition is out now for Windows 10",
    "/Detroit: Become Human released on PC",
    "/No Man's Sky great Unity project",
    "/XBOX 360 unavailable to buy on Amazon...",
    "/Valorant is the best shooter in 2020",
];
export default blogPaths;
